apiVersion: apps/v1
kind: Deployment
metadata:
  name: fpsa-site
  namespace: fpsa
spec:
  selector:
    matchLabels:
      app: fpsa-site
      tier: frontend
  replicas: 1
  template:
    metadata:
      name: fpsa-site
      namespace: fpsa
      labels:
        app: fpsa-site
        tier: frontend
    spec:
      containers:
      - name: fpsa-site
        image: svfpsa/site:{{site_version}}
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: VUE_APP_API_URL
          value: https://api.fpsa.nl
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: fpsa-site-service
  namespace: fpsa
spec:
  type: NodePort
  selector:
    app: fpsa-site
    tier: frontend
  ports:
    - port: 8080
