apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  namespace: fpsa
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      tier: frontend
  replicas: 1
  template:
    metadata:
      name: {{ .Chart.Name }}
      namespace: fpsa
      labels:
        app: {{ .Chart.Name }}
        tier: frontend
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: svfpsa/site:{{.Values.tag}}
        ports:
        - containerPort: 8080
