apiVersion: v1
kind: Service
metadata:
  name: {{.Values.Version}}{{ .Chart.Name }}-service
  namespace: fpsa
spec:
  type: NodePort
  selector:
    app: {{.Values.Version}}{{ .Chart.Name }}
    tier: frontend
  ports:
    - port: 8080