name: Deployment

on:
  push:
    branches: [ master, beta ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build env file
      run: echo "VUE_APP_API_URL=https://api.fpsa.nl" > .env

# Build and test project
    - name: Install packages
      run: npm i
    - name: build project
      run: npm run build

# Dockerize project
    - name: Docker login
      env:
        Username: ${{secrets.DOCKER_USERNAME}}
        Password: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $Username -p $Password
    
    - name: Docker build
      run: docker build -t svfpsa/site:$GITHUB_SHA -f Dockerfile .;
    
    - name: Docker publish
      run: docker push svfpsa/site:$GITHUB_SHA

# Deploy container
    - name: Deploy production
      uses: 'deliverybot/helm@master'
      if: endsWith(github.ref, '/master')
      with:
        release: 'fpsa-site'
        namespace: 'fpsa'
        chart: 'k8b'
        helm: 'helm3'
        token: '${{ github.token }}'
        values: |
          tag: '${{ github.sha }}'
          Version: ''
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

    - name: Deploy beta
      uses: 'deliverybot/helm@master'
      if: endsWith(github.ref, '/beta')
      with:
        release: 'beta-fpsa-site'
        namespace: 'fpsa'
        chart: 'k8b'
        helm: 'helm3'
        token: '${{ github.token }}'
        values: |
          tag: '${{ github.sha }}'
          Version: 'beta-'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
