/**
 * FPSA API
 * FPSA API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@fpsa.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AgendaSummaryDTO { 
    id: number;
    location: string;
    date: string;
    title: string;
    summary: string;
}
