/**
 * FPSA API
 * FPSA API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@fpsa.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserSummaryDTO { 
    id: number;
    fullName: string;
    email: string;
}
